// Generated by gencpp from file krsbi2025/DribbleModule.msg
// DO NOT EDIT!


#ifndef KRSBI2025_MESSAGE_DRIBBLEMODULE_H
#define KRSBI2025_MESSAGE_DRIBBLEMODULE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krsbi2025
{
template <class ContainerAllocator>
struct DribbleModule_
{
  typedef DribbleModule_<ContainerAllocator> Type;

  DribbleModule_()
    : left_motor_cw(0.0)
    , left_motor_ccw(0.0)
    , right_motor_cw(0.0)
    , right_motor_ccw(0.0)  {
    }
  DribbleModule_(const ContainerAllocator& _alloc)
    : left_motor_cw(0.0)
    , left_motor_ccw(0.0)
    , right_motor_cw(0.0)
    , right_motor_ccw(0.0)  {
  (void)_alloc;
    }



   typedef double _left_motor_cw_type;
  _left_motor_cw_type left_motor_cw;

   typedef double _left_motor_ccw_type;
  _left_motor_ccw_type left_motor_ccw;

   typedef double _right_motor_cw_type;
  _right_motor_cw_type right_motor_cw;

   typedef double _right_motor_ccw_type;
  _right_motor_ccw_type right_motor_ccw;





  typedef boost::shared_ptr< ::krsbi2025::DribbleModule_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krsbi2025::DribbleModule_<ContainerAllocator> const> ConstPtr;

}; // struct DribbleModule_

typedef ::krsbi2025::DribbleModule_<std::allocator<void> > DribbleModule;

typedef boost::shared_ptr< ::krsbi2025::DribbleModule > DribbleModulePtr;
typedef boost::shared_ptr< ::krsbi2025::DribbleModule const> DribbleModuleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krsbi2025::DribbleModule_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krsbi2025::DribbleModule_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::krsbi2025::DribbleModule_<ContainerAllocator1> & lhs, const ::krsbi2025::DribbleModule_<ContainerAllocator2> & rhs)
{
  return lhs.left_motor_cw == rhs.left_motor_cw &&
    lhs.left_motor_ccw == rhs.left_motor_ccw &&
    lhs.right_motor_cw == rhs.right_motor_cw &&
    lhs.right_motor_ccw == rhs.right_motor_ccw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::krsbi2025::DribbleModule_<ContainerAllocator1> & lhs, const ::krsbi2025::DribbleModule_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace krsbi2025

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::DribbleModule_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::DribbleModule_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::DribbleModule_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::DribbleModule_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::DribbleModule_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::DribbleModule_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krsbi2025::DribbleModule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8999603c5bbfafec517920ea2273e31e";
  }

  static const char* value(const ::krsbi2025::DribbleModule_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8999603c5bbfafecULL;
  static const uint64_t static_value2 = 0x517920ea2273e31eULL;
};

template<class ContainerAllocator>
struct DataType< ::krsbi2025::DribbleModule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krsbi2025/DribbleModule";
  }

  static const char* value(const ::krsbi2025::DribbleModule_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krsbi2025::DribbleModule_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left_motor_cw\n"
"float64 left_motor_ccw\n"
"float64 right_motor_cw\n"
"float64 right_motor_ccw\n"
;
  }

  static const char* value(const ::krsbi2025::DribbleModule_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krsbi2025::DribbleModule_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_motor_cw);
      stream.next(m.left_motor_ccw);
      stream.next(m.right_motor_cw);
      stream.next(m.right_motor_ccw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DribbleModule_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krsbi2025::DribbleModule_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krsbi2025::DribbleModule_<ContainerAllocator>& v)
  {
    s << indent << "left_motor_cw: ";
    Printer<double>::stream(s, indent + "  ", v.left_motor_cw);
    s << indent << "left_motor_ccw: ";
    Printer<double>::stream(s, indent + "  ", v.left_motor_ccw);
    s << indent << "right_motor_cw: ";
    Printer<double>::stream(s, indent + "  ", v.right_motor_cw);
    s << indent << "right_motor_ccw: ";
    Printer<double>::stream(s, indent + "  ", v.right_motor_ccw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRSBI2025_MESSAGE_DRIBBLEMODULE_H
