// Generated by gencpp from file krsbi2025/ObjectDifference.msg
// DO NOT EDIT!


#ifndef KRSBI2025_MESSAGE_OBJECTDIFFERENCE_H
#define KRSBI2025_MESSAGE_OBJECTDIFFERENCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krsbi2025
{
template <class ContainerAllocator>
struct ObjectDifference_
{
  typedef ObjectDifference_<ContainerAllocator> Type;

  ObjectDifference_()
    : object_type()
    , x_difference(0)  {
    }
  ObjectDifference_(const ContainerAllocator& _alloc)
    : object_type(_alloc)
    , x_difference(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_type_type;
  _object_type_type object_type;

   typedef int16_t _x_difference_type;
  _x_difference_type x_difference;





  typedef boost::shared_ptr< ::krsbi2025::ObjectDifference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krsbi2025::ObjectDifference_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDifference_

typedef ::krsbi2025::ObjectDifference_<std::allocator<void> > ObjectDifference;

typedef boost::shared_ptr< ::krsbi2025::ObjectDifference > ObjectDifferencePtr;
typedef boost::shared_ptr< ::krsbi2025::ObjectDifference const> ObjectDifferenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krsbi2025::ObjectDifference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krsbi2025::ObjectDifference_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::krsbi2025::ObjectDifference_<ContainerAllocator1> & lhs, const ::krsbi2025::ObjectDifference_<ContainerAllocator2> & rhs)
{
  return lhs.object_type == rhs.object_type &&
    lhs.x_difference == rhs.x_difference;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::krsbi2025::ObjectDifference_<ContainerAllocator1> & lhs, const ::krsbi2025::ObjectDifference_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace krsbi2025

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::ObjectDifference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::ObjectDifference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::ObjectDifference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::ObjectDifference_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::ObjectDifference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::ObjectDifference_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krsbi2025::ObjectDifference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9805b6fd573c60efaf93d832bb6035b2";
  }

  static const char* value(const ::krsbi2025::ObjectDifference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9805b6fd573c60efULL;
  static const uint64_t static_value2 = 0xaf93d832bb6035b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::krsbi2025::ObjectDifference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krsbi2025/ObjectDifference";
  }

  static const char* value(const ::krsbi2025::ObjectDifference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krsbi2025::ObjectDifference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_type\n"
"int16 x_difference\n"
;
  }

  static const char* value(const ::krsbi2025::ObjectDifference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krsbi2025::ObjectDifference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_type);
      stream.next(m.x_difference);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDifference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krsbi2025::ObjectDifference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krsbi2025::ObjectDifference_<ContainerAllocator>& v)
  {
    s << indent << "object_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_type);
    s << indent << "x_difference: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x_difference);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRSBI2025_MESSAGE_OBJECTDIFFERENCE_H
