// Generated by gencpp from file krsbi2025/PID.msg
// DO NOT EDIT!


#ifndef KRSBI2025_MESSAGE_PID_H
#define KRSBI2025_MESSAGE_PID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krsbi2025
{
template <class ContainerAllocator>
struct PID_
{
  typedef PID_<ContainerAllocator> Type;

  PID_()
    : outw(0.0)
    , outy(0.0)  {
    }
  PID_(const ContainerAllocator& _alloc)
    : outw(0.0)
    , outy(0.0)  {
  (void)_alloc;
    }



   typedef float _outw_type;
  _outw_type outw;

   typedef float _outy_type;
  _outy_type outy;





  typedef boost::shared_ptr< ::krsbi2025::PID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krsbi2025::PID_<ContainerAllocator> const> ConstPtr;

}; // struct PID_

typedef ::krsbi2025::PID_<std::allocator<void> > PID;

typedef boost::shared_ptr< ::krsbi2025::PID > PIDPtr;
typedef boost::shared_ptr< ::krsbi2025::PID const> PIDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krsbi2025::PID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krsbi2025::PID_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::krsbi2025::PID_<ContainerAllocator1> & lhs, const ::krsbi2025::PID_<ContainerAllocator2> & rhs)
{
  return lhs.outw == rhs.outw &&
    lhs.outy == rhs.outy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::krsbi2025::PID_<ContainerAllocator1> & lhs, const ::krsbi2025::PID_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace krsbi2025

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::PID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::PID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::PID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::PID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::PID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::PID_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krsbi2025::PID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "379ea6ebbb86291b6b9b88c13f43196d";
  }

  static const char* value(const ::krsbi2025::PID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x379ea6ebbb86291bULL;
  static const uint64_t static_value2 = 0x6b9b88c13f43196dULL;
};

template<class ContainerAllocator>
struct DataType< ::krsbi2025::PID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krsbi2025/PID";
  }

  static const char* value(const ::krsbi2025::PID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krsbi2025::PID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 outw\n"
"float32 outy\n"
;
  }

  static const char* value(const ::krsbi2025::PID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krsbi2025::PID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.outw);
      stream.next(m.outy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krsbi2025::PID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krsbi2025::PID_<ContainerAllocator>& v)
  {
    s << indent << "outw: ";
    Printer<float>::stream(s, indent + "  ", v.outw);
    s << indent << "outy: ";
    Printer<float>::stream(s, indent + "  ", v.outy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRSBI2025_MESSAGE_PID_H
