// Generated by gencpp from file krsbi2025/Error.msg
// DO NOT EDIT!


#ifndef KRSBI2025_MESSAGE_ERROR_H
#define KRSBI2025_MESSAGE_ERROR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krsbi2025
{
template <class ContainerAllocator>
struct Error_
{
  typedef Error_<ContainerAllocator> Type;

  Error_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , sway(0.0)
    , depth(0.0)
    , pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)  {
    }
  Error_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , sway(0.0)
    , depth(0.0)
    , pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _sway_type;
  _sway_type sway;

   typedef float _depth_type;
  _depth_type depth;

   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;

   typedef float _pos_z_type;
  _pos_z_type pos_z;





  typedef boost::shared_ptr< ::krsbi2025::Error_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krsbi2025::Error_<ContainerAllocator> const> ConstPtr;

}; // struct Error_

typedef ::krsbi2025::Error_<std::allocator<void> > Error;

typedef boost::shared_ptr< ::krsbi2025::Error > ErrorPtr;
typedef boost::shared_ptr< ::krsbi2025::Error const> ErrorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krsbi2025::Error_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krsbi2025::Error_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::krsbi2025::Error_<ContainerAllocator1> & lhs, const ::krsbi2025::Error_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.sway == rhs.sway &&
    lhs.depth == rhs.depth &&
    lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.pos_z == rhs.pos_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::krsbi2025::Error_<ContainerAllocator1> & lhs, const ::krsbi2025::Error_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace krsbi2025

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::Error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::Error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::Error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::Error_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::Error_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krsbi2025::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cbf2903a11fcb412a88b4edd43ccaec";
  }

  static const char* value(const ::krsbi2025::Error_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cbf2903a11fcb41ULL;
  static const uint64_t static_value2 = 0x2a88b4edd43ccaecULL;
};

template<class ContainerAllocator>
struct DataType< ::krsbi2025::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krsbi2025/Error";
  }

  static const char* value(const ::krsbi2025::Error_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krsbi2025::Error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
"float32 sway\n"
"float32 depth\n"
"float32 pos_x\n"
"float32 pos_y\n"
"float32 pos_z\n"
;
  }

  static const char* value(const ::krsbi2025::Error_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krsbi2025::Error_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.sway);
      stream.next(m.depth);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.pos_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Error_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krsbi2025::Error_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krsbi2025::Error_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "sway: ";
    Printer<float>::stream(s, indent + "  ", v.sway);
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
    s << indent << "pos_z: ";
    Printer<float>::stream(s, indent + "  ", v.pos_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRSBI2025_MESSAGE_ERROR_H
