// Generated by gencpp from file krsbi2025/Wheel.msg
// DO NOT EDIT!


#ifndef KRSBI2025_MESSAGE_WHEEL_H
#define KRSBI2025_MESSAGE_WHEEL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krsbi2025
{
template <class ContainerAllocator>
struct Wheel_
{
  typedef Wheel_<ContainerAllocator> Type;

  Wheel_()
    : left_wheel_cw(0.0)
    , left_wheel_ccw(0.0)
    , right_wheel_cw(0.0)
    , right_wheel_ccw(0.0)
    , bottom_wheel_cw(0.0)
    , bottom_wheel_ccw(0.0)  {
    }
  Wheel_(const ContainerAllocator& _alloc)
    : left_wheel_cw(0.0)
    , left_wheel_ccw(0.0)
    , right_wheel_cw(0.0)
    , right_wheel_ccw(0.0)
    , bottom_wheel_cw(0.0)
    , bottom_wheel_ccw(0.0)  {
  (void)_alloc;
    }



   typedef double _left_wheel_cw_type;
  _left_wheel_cw_type left_wheel_cw;

   typedef double _left_wheel_ccw_type;
  _left_wheel_ccw_type left_wheel_ccw;

   typedef double _right_wheel_cw_type;
  _right_wheel_cw_type right_wheel_cw;

   typedef double _right_wheel_ccw_type;
  _right_wheel_ccw_type right_wheel_ccw;

   typedef double _bottom_wheel_cw_type;
  _bottom_wheel_cw_type bottom_wheel_cw;

   typedef double _bottom_wheel_ccw_type;
  _bottom_wheel_ccw_type bottom_wheel_ccw;





  typedef boost::shared_ptr< ::krsbi2025::Wheel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krsbi2025::Wheel_<ContainerAllocator> const> ConstPtr;

}; // struct Wheel_

typedef ::krsbi2025::Wheel_<std::allocator<void> > Wheel;

typedef boost::shared_ptr< ::krsbi2025::Wheel > WheelPtr;
typedef boost::shared_ptr< ::krsbi2025::Wheel const> WheelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krsbi2025::Wheel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krsbi2025::Wheel_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::krsbi2025::Wheel_<ContainerAllocator1> & lhs, const ::krsbi2025::Wheel_<ContainerAllocator2> & rhs)
{
  return lhs.left_wheel_cw == rhs.left_wheel_cw &&
    lhs.left_wheel_ccw == rhs.left_wheel_ccw &&
    lhs.right_wheel_cw == rhs.right_wheel_cw &&
    lhs.right_wheel_ccw == rhs.right_wheel_ccw &&
    lhs.bottom_wheel_cw == rhs.bottom_wheel_cw &&
    lhs.bottom_wheel_ccw == rhs.bottom_wheel_ccw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::krsbi2025::Wheel_<ContainerAllocator1> & lhs, const ::krsbi2025::Wheel_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace krsbi2025

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::Wheel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::Wheel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::Wheel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::Wheel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::Wheel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::Wheel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krsbi2025::Wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23cc0e6db082887e7d28f8d9255b33a9";
  }

  static const char* value(const ::krsbi2025::Wheel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23cc0e6db082887eULL;
  static const uint64_t static_value2 = 0x7d28f8d9255b33a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::krsbi2025::Wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krsbi2025/Wheel";
  }

  static const char* value(const ::krsbi2025::Wheel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krsbi2025::Wheel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left_wheel_cw\n"
"float64 left_wheel_ccw\n"
"float64 right_wheel_cw\n"
"float64 right_wheel_ccw\n"
"float64 bottom_wheel_cw\n"
"float64 bottom_wheel_ccw\n"
;
  }

  static const char* value(const ::krsbi2025::Wheel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krsbi2025::Wheel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_wheel_cw);
      stream.next(m.left_wheel_ccw);
      stream.next(m.right_wheel_cw);
      stream.next(m.right_wheel_ccw);
      stream.next(m.bottom_wheel_cw);
      stream.next(m.bottom_wheel_ccw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Wheel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krsbi2025::Wheel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krsbi2025::Wheel_<ContainerAllocator>& v)
  {
    s << indent << "left_wheel_cw: ";
    Printer<double>::stream(s, indent + "  ", v.left_wheel_cw);
    s << indent << "left_wheel_ccw: ";
    Printer<double>::stream(s, indent + "  ", v.left_wheel_ccw);
    s << indent << "right_wheel_cw: ";
    Printer<double>::stream(s, indent + "  ", v.right_wheel_cw);
    s << indent << "right_wheel_ccw: ";
    Printer<double>::stream(s, indent + "  ", v.right_wheel_ccw);
    s << indent << "bottom_wheel_cw: ";
    Printer<double>::stream(s, indent + "  ", v.bottom_wheel_cw);
    s << indent << "bottom_wheel_ccw: ";
    Printer<double>::stream(s, indent + "  ", v.bottom_wheel_ccw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRSBI2025_MESSAGE_WHEEL_H
