// Generated by gencpp from file krsbi2025/BNO_ENC.msg
// DO NOT EDIT!


#ifndef KRSBI2025_MESSAGE_BNO_ENC_H
#define KRSBI2025_MESSAGE_BNO_ENC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace krsbi2025
{
template <class ContainerAllocator>
struct BNO_ENC_
{
  typedef BNO_ENC_<ContainerAllocator> Type;

  BNO_ENC_()
    : compas(0.0)
    , x(0.0)
    , y(0.0)  {
    }
  BNO_ENC_(const ContainerAllocator& _alloc)
    : compas(0.0)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef float _compas_type;
  _compas_type compas;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::krsbi2025::BNO_ENC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::krsbi2025::BNO_ENC_<ContainerAllocator> const> ConstPtr;

}; // struct BNO_ENC_

typedef ::krsbi2025::BNO_ENC_<std::allocator<void> > BNO_ENC;

typedef boost::shared_ptr< ::krsbi2025::BNO_ENC > BNO_ENCPtr;
typedef boost::shared_ptr< ::krsbi2025::BNO_ENC const> BNO_ENCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::krsbi2025::BNO_ENC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::krsbi2025::BNO_ENC_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::krsbi2025::BNO_ENC_<ContainerAllocator1> & lhs, const ::krsbi2025::BNO_ENC_<ContainerAllocator2> & rhs)
{
  return lhs.compas == rhs.compas &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::krsbi2025::BNO_ENC_<ContainerAllocator1> & lhs, const ::krsbi2025::BNO_ENC_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace krsbi2025

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::BNO_ENC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::krsbi2025::BNO_ENC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::BNO_ENC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::krsbi2025::BNO_ENC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::BNO_ENC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::krsbi2025::BNO_ENC_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::krsbi2025::BNO_ENC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "444cbdcc09ffd1f44774ec331f0b39de";
  }

  static const char* value(const ::krsbi2025::BNO_ENC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x444cbdcc09ffd1f4ULL;
  static const uint64_t static_value2 = 0x4774ec331f0b39deULL;
};

template<class ContainerAllocator>
struct DataType< ::krsbi2025::BNO_ENC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "krsbi2025/BNO_ENC";
  }

  static const char* value(const ::krsbi2025::BNO_ENC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::krsbi2025::BNO_ENC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 compas\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::krsbi2025::BNO_ENC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::krsbi2025::BNO_ENC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.compas);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BNO_ENC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::krsbi2025::BNO_ENC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::krsbi2025::BNO_ENC_<ContainerAllocator>& v)
  {
    s << indent << "compas: ";
    Printer<float>::stream(s, indent + "  ", v.compas);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KRSBI2025_MESSAGE_BNO_ENC_H
